# Random Forest Classifier

In [2]:
#Importing the Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
from sklearn.datasets import load_digits

In [5]:
digits = load_digits()

In [6]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [8]:
#Checking the target values
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [9]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [11]:
#For target names output
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
digits_df = pd.DataFrame(digits.data)

In [14]:
#Datatframe with independent values\Features
digits_df

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [15]:
digits_df['target'] = digits.target

In [17]:
#Complete df with target values
digits_df

0    1     2     3     4     5    6    7    8    9  ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63  target  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0       1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0       2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0       3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0       4  
...   ...  ...   ...   ...   ...  ...  ...     ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0       9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0       0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0       8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0       9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0       8  

[1797 rows x 65 columns]

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

In [43]:
#Train_test split 90/10 %
x_train, x_test, y_train, y_test = train_test_split(digits_df.drop('target', axis= 'columns'), digits_df.target, test_size= 0.1) 

In [44]:
#Checking the frequency counts
digits_df.value_counts().sort_index()

0    1    2     3     4     5     6     7    8    9     10    11    12    13    14    15   16   17    18    19    20    21    22    23   24   25   26    27    28    29    30   31   32   33   34    35    36    37    38   39   40   41   42    43    44    45    46   47   48   49   50    51    52    53    54   55   56   57   58    59    60    61    62   63   target
0.0  0.0  0.0   0.0   3.0   14.0  3.0   0.0  0.0  0.0   0.0   1.0   14.0  16.0  5.0   0.0  0.0  1.0   9.0   15.0  16.0  16.0  4.0   0.0  0.0  4.0  12.0  7.0   3.0   16.0  4.0  0.0  0.0  0.0  0.0   0.0   4.0   16.0  4.0  0.0  0.0  0.0  0.0   0.0   4.0   16.0  4.0  0.0  0.0  0.0  0.0   0.0   6.0   16.0  4.0  0.0  0.0  0.0  0.0   0.0   5.0   16.0  4.0  0.0  1         1
                            15.0  6.0   0.0  0.0  0.0   0.0   0.0   11.0  16.0  7.0   0.0  0.0  0.0   0.0   9.0   16.0  16.0  4.0   0.0  0.0  0.0  10.0  16.0  16.0  16.0  4.0  0.0  0.0  4.0  16.0  7.0   8.0   16.0  4.0  0.0  0.0  1.0  4.0   0.0   10.0  16.0  2.0  0.0

In [45]:
print(x_train.shape)

(1617, 64)


In [46]:
print(x_test.shape)

(180, 64)


In [47]:
randomforest = RandomForestClassifier(n_estimators= 100)

In [48]:
randomforest.fit(x_train, y_train)

RandomForestClassifier()

In [49]:
predicted = randomforest.predict(x_test)

In [50]:
#predicted Output
predicted

array([0, 1, 4, 6, 7, 8, 3, 8, 0, 6, 8, 9, 1, 6, 8, 0, 7, 0, 7, 2, 7, 9,
       6, 8, 9, 0, 1, 0, 9, 3, 8, 1, 8, 3, 9, 6, 5, 9, 8, 4, 4, 1, 8, 6,
       3, 3, 9, 5, 4, 8, 1, 5, 1, 9, 5, 3, 3, 6, 1, 8, 9, 6, 4, 3, 1, 3,
       4, 3, 3, 4, 3, 5, 0, 9, 5, 3, 7, 2, 8, 3, 7, 1, 4, 4, 0, 5, 2, 9,
       4, 4, 2, 4, 6, 4, 7, 7, 4, 7, 1, 1, 4, 9, 0, 3, 2, 6, 4, 8, 4, 0,
       5, 8, 1, 0, 4, 3, 5, 4, 0, 6, 4, 1, 9, 5, 9, 8, 8, 5, 2, 5, 8, 0,
       3, 8, 8, 1, 5, 3, 6, 7, 9, 9, 2, 8, 8, 3, 7, 8, 0, 6, 6, 5, 3, 9,
       2, 2, 3, 0, 6, 9, 1, 3, 0, 6, 9, 4, 3, 9, 9, 6, 3, 0, 6, 0, 3, 5,
       0, 9, 4, 7])

In [51]:
print(classification_report(y_test, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.81      1.00      0.90        13
           2       1.00      0.90      0.95        10
           3       1.00      1.00      1.00        25
           4       1.00      0.96      0.98        23
           5       0.87      1.00      0.93        13
           6       1.00      0.95      0.97        19
           7       1.00      1.00      1.00        12
           8       0.95      0.91      0.93        23
           9       0.95      0.91      0.93        23

    accuracy                           0.96       180
   macro avg       0.96      0.96      0.96       180
weighted avg       0.97      0.96      0.96       180



In [52]:
#Confusion matrix
print(confusion_matrix(y_test, predicted))

[[19  0  0  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0  0]
 [ 0  1  9  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0]
 [ 0  0  0  0 22  0  0  0  0  1]
 [ 0  0  0  0  0 13  0  0  0  0]
 [ 0  0  0  0  0  0 18  0  1  0]
 [ 0  0  0  0  0  0  0 12  0  0]
 [ 0  2  0  0  0  0  0  0 21  0]
 [ 0  0  0  0  0  2  0  0  0 21]]
